// vue-web-ui/src/components/box.vue
<template>
  <div :class=className>
    <slot />
  </div>
</template>

<script>
import {defaultTheme, paddingClassName} from '@transclusion/css'

export default {
  name: 'box',
  props: ['padding', 'paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft'],
  data (comp) {
    return {
      className: paddingClassName(defaultTheme, comp)
    }
  }
}
</script>

// react-web-ui/src/components/box.tsx
import {PaddingProps} from '@transclusion/css'
import React from 'react'
import {usePaddingClass} from '../providers/theme'
import {classNames, getCompPath} from './_helpers'
import {ComponentProps} from './types'

export interface BoxProps extends ComponentProps, PaddingProps {}

export function Box(props: BoxProps & React.HTMLProps<HTMLSpanElement>) {
  const {
    as: asProp,
    padding,
    paddingTop,
    paddingRight,
    paddingBottom,
    paddingLeft,
    ...restProps
  } = props

  const className = classNames(
    props.className,
    usePaddingClass({padding, paddingTop, paddingRight, paddingBottom, paddingLeft})
  )

  const boxProps = {
    ...restProps,
    className,
    'data-c': getCompPath('box', props)
  }

  return React.createElement(asProp || 'div', boxProps)
}
